config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, :only => [:new, :create, :destroy, :update, :edit] do
    resources :groups do
      resources :events
    end
  end

  get 'user' => 'users#show'

  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  get 'auth/logout' => 'auth#logout'
  get 'auth/failure' => 'auth#failure'
  get 'auth/:provider/callback' => 'auth#callback'
  get 'auth/signup' => 'auth#signup'

  get 'textresponse' => 'events#textmessage'
  get 'nudge/:current_user_id/:user_id/:event_id' => 'events#nudge'
  get 'shade/:current_user_id/:user_id/:event_id' => 'events#shade'

  get '*unmatched_route' => 'errors#not_found'
  get '/404' => 'errors#not_found', via: :all
  get '/422' => 'errors#not_acceptable', via: :all
  get '/500' => 'errors#internal_server_error', via: :all

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :events
  has_many :memberships

  validates :name,
  :on => :create,
  :presence => true

  validates :size,
  :on => :create,
  :presence => true,
  numericality: true



end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    if current_user
      @user = current_user
      @group = Group.new
      @event = Event.new
      unless @user.groups.empty?
        @groups = @user.groups
        puts @groups
      end
    else
      redirect_to root_path
    end
  end

  def create
      # render :plain => params
    user = current_user
    if params[:group][:size].to_i.is_a? Integer
        unless params[:group][:image] == nil
          uploaded_file = params[:group][:image].path
        else
          uploaded_file = "#{Rails.root}/app/assets/images/daysie-chain-logo.png"
        end
        cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
        cloudinary_file = cloudinary_file["public_id"];
      group = Group.create(:name => params[:group][:name], :size => params[:group][:size].to_i, :status => params[:group][:status], :image => cloudinary_file)
      if group
        user.groups << group
        event = Event.create(:name => params[:event][:name], :desc => params[:event][:desc], :max => params[:event][:max], :loc => params[:event][:loc], :date => params[:event][:date], :time => params[:event][:time])
        user.groups.find(group.id).events << event
        user.memberships << group.memberships.create(admin:true)
      else
        flash[:danger] = "Please complete fill out all required fields"
      end
    else
      flash[:danger] = "Please enter a valid size"
    end
    redirect_to user_groups_path(@current_user.id)
  end

  def show
    @user = current_user
    @group = current_user.memberships.find_by_group_id(params[:id]).group
    @members = @group.memberships
    render layout: false
  end

end

app/views/groups/index.html.erb
<!-- <img id="center_pic" src="http://perceptualunderstanding.files.wordpress.com/2012/02/scan-e1328633637316.jpg?w=413&h=418"> -->

<div class="row">

  <div id="buttoncontainer">
  <a class="btn" id="create_group_button" data-toggle="modal" href='#create_group'><span class="glyphicon glyphicon-plus"></span>   <strong>Create a new Group</strong></a>
    <% if @current_user.memberships %>
      <% @current_user.memberships.each do |i| %>
        <% @idx = i.id %>
        <div class="radial_button" id="<%= @idx %>">
            <%= cl_image_tag(i.group[:image], :class => "group_image") %>
            <p><strong><%= i.group.name %></strong></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <% if @current_user.memberships %>
    <% @current_user.memberships.each do |i| %>
      <% @idx = i.id %>
        <div class="radmenu">
          <a href="#" id="menu<%= @idx %>" group-id="<%= i.group_id%>" class="show" ><%= cl_image_tag(i.group[:image], :class=>"daysie_image") %></a>
          <ul>
            <li class="subli">
              <a class="submenus" data-toggle="modal" href="<%= new_user_path(i) %>" id="<%= @idx %>" data-target="#add_user" class= "group_user_add"><i class="fa fa-user-plus fa-3x"></i></a>
              <ul>
              </ul>
            </li>
            <li class="subli">
              <a class="submenus" data-toggle="modal" data-target='#create_event' href="<%=new_user_group_event_path(@current_user,i.group)%>" class="event_add">Add an Event</a>
              <ul>
              </ul>
            </li>
            <li class="subli">
              <a class="submenus" data-toggle="modal" href="<%= user_group_path(@current_user, i.group) %>" id="<%= i.group.id %>" data-target="#group_users_show">View Members</a>
            </li>

            <% i.group.events.each do |j| %>

              <% if Attendance.find_by_event_id(j.id) %>
                <li class="subli">
                  <a class="submenus" data-toggle="modal" class="event_invite" href="<%= user_group_event_path(@current_user,i.group,j)%>" data-target='#event_show'><%= j.name %></a>
                </li>
              <% else %>
                <li class="subli">
                  <a class="submenus" data-toggle="modal" class="event_invite" href="<%= edit_user_group_event_path(@current_user,i.group,j)%>" data-target='#event_invite'><%= j.name %></a>
                </li>
              <% end %>

            <% end %>
          </ul>
        </div>
    <% end %>
  <% end %>

   <!-- Below here be the realm of modals, ya hear? -->

   <div class="modal fade my_modal_class" id="create_group">
    <div class="modal-dialog">
      <div class="modal-content my_modal_content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Create a Group</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for [@user, @group], :html => { :id => "group_form" } do |f| %>
          <%= f.text_field :name, placeholder: "e.g. Party Girlz" %>
          <%= f.text_field :size, label: "Maximum number of group members", placeholder: "The fewer the merrier!" %>
          <%= f.file_field :image %>
          <hr>
          <h4> What is it that you lovely people do together? </h4>
          <small> Don't stress yourself out: you can add more events to this group at any time. </small>
          <%= bootstrap_form_for :event, :html => { :id => "event_form" } do |f| %>
            <%= f.text_field :name, :label => "Event Name", placeholder: "Something simple and recognizable." %>
            <%= f.text_field :desc, :label => "Description", placeholder: "Short and sweet works best." %>
            <%= f.text_field :loc, :label => "Location", placeholder: "Where's it gonna be?" %>
          <span class="pull-right">
            <% end %>
            <% end %>

            <button type="button"  class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" id="group_submit" class="btn btn-primary">Save changes</button>
          </span>
        </div>
        <div class="modal-footer">
        </div>

      </div>
    </div>
  </div>

  <% if @groups %>
    <div class="fade modal my_modal_class" id="event_invite">
      <div class="modal-dialog">
        <div class="modal-content">
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->


    <div class="fade modal my_modal_class" id="event_show">
      <div class="modal-dialog">
        <div class="modal-content">
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div>

    <div class="fade modal my_modal_class" id="group_users_show">
      <div class="modal-dialog">
        <div class="modal-content">
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  <% end %>

  <div class="fade modal my_modal_class" id="create_event">
    <div class="modal-dialog">
      <div class="modal-content">

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <div class="modal fade my_modal_class" id="add_user">
    <div class="modal-dialog">
      <div class="modal-content">

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal  -->
</div>

app/views/groups/show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title"><%= @group.name %></h4>
</div>
<div class="modal-body event-modal" id="members 0">
  <div class="row">
    <div class="col-md-12">
      <div class="admins">
      <h5> Admins </h5>
      <ul id="group_admins" class="group list-group">
        <% @members.each_with_index do |j, idx| %>
          <% if j.admin %>
            <li class="member list-group-item" id="<%=j.user.id%>"> <%= j.user.firstname %> </li>
          <% end %>
        <% end %>
        </ul>
      </div>
      <hr>
      <div class="members">
        <h5> Members </h5>
        <ul id="group_members" class="group list-group">
        <% @members.each_with_index do |i, idx| %>
          <% if i.admin == false %>
          <li class="member list-group-item" id="<%=i.user.id%>"> <%= i.user.firstname %> </li>
          <% end %>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-12">
      <div class="trash">
        <i class="fa fa-trash pull-right fa-3x"></i>
        <ul id="group_member_delete" class="group list-group">

        </ul>
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>


<script>
<% membership = @current_user.memberships.find_by_group_id(params[:id]) %>
<% if @current_user.id == membership.group.user_id %>
  $("#group_members, #group_admins, #group_member_delete").sortable({
    connectWith: ".group",
    receive: function(event, ui) {
      var groupId = <%=@group.id %>

      // var serialized = $("#group_members").sortable('serialize') + "&" + $("#group_admins").sortable('serialize') + "&groupId=" + groupId;
      var id = ui.item.attr("id")
      $.ajax({
        method: "put",
        data: {
          members:$("#group_members").sortable('toArray'),
          admins:$("#group_admins").sortable('toArray'),
          deletions:$("#group_member_delete").sortable('toArray'),
          groupId: groupId
        },
        url: "/users/"+id
      }).done(function(data){
        $("#group_member_delete").children().fadeOut(400)
        console.log(data)
      })
    }
  }).disableSelection();
<% end %>
</script>